---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all

platforms:
  - name: ubuntu/vivid64
    driver_config:
      box: ubuntu/vivid64
      box_url: https://atlas.hashicorp.com/ubuntu/vivid64

  - name: centos/7
    driver_config:
      box: centos/7
      box_url: https://atlas.hashicorp.com/centos/7

suites:
  - name: default
