---
- hosts: all
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - name: Ensure updated
      raw: apk update
    - name: Ensure Python and pip are installed
      raw: apk add python2 py2-pip

- hosts: all
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - {role: robertdebock.core_dependencies, tags: ['alpine']}
